services:
  db:
    image: postgres:16-alpine
    container_name: mass_manager_postgres_db
    environment:
      POSTGRES_DB: mass_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - massmanager-network

  app:
    build: .
    container_name: mass_manager_app
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mass_manager_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - massmanager-network

volumes:
  postgres_data:

networks:
  massmanager-network:
    driver: bridge
