spring.application.name=massmanager

# Configuracion dinamica de la base de datos
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/mass_manager_db}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

#Configuracion desde la pc de 4Z4C
# spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/mass_manager_db?sslmode=disable&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.url=jdbc:postgresql://localhost:5432/mass_manager_db
spring.datasource.username=admin
spring.datasource.password=admin123

# JPA / Hibernate Forzado para crear las tablas al iniciar
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del Servidor
server.port=8085
jwt.secret=miClaveSecretaSuperSeguraParaMassManager2026
jwt.expiration=86400000